### ISSUE TITLE
The link describe changes is not working

### ISSUE THREAD

**Issue by The27** [WuBoytH/The-WuBoy-Ultimate-Modpack#1]
- https://tinyurl.com/WuBoyModpack
 - https://tinyurl.com/WuBoyModpackMusic
These two links doesn't work

**Comment by WuBoytH** [comment]
They still seem to work for me, I'm not sure why it wouldn't work for you

**Comment by The27** [comment]
Uh oh, so could you post the full link? Maybe I'm in China and tinyurl got blocked I guess...But it also doesn't work for my friend in Japan so it's weird.

**Comment by WuBoytH** [comment]
Oh that's interesting, it leads to Google drive links so I'm not sure if you can see those in China
I'm not at my computer but here are both direct links to the Google drive pages
https://docs.google.com/document/d/1QAoHsBroOPDXOJQcSUjp4endY1l8ma0Nxjn5FXmkYAY/edit?usp=drivesdk
https://docs.google.com/spreadsheets/d/1ksQ62YmcwtFHose3rSsVpEIZMuv3BQfnBP4lzqM1wbY/edit?usp=drivesdk
Hopefully those work for you

**Comment by The27** [comment]
Ah, it works! (Because I have tools to connect Google Drive lmao)
Thank you a lot!

**Comment by WuBoytH** [comment]
No problem, enjoy the modpack 👍
